name: Fetch moonshot count

permissions:
  contents: write

on:
  schedule:
    # every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: {}

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # allow pushing using the provided token
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run fetch script
        run: |
          python app.py --once --csv-file data.csv --min-count 400

      - name: Upload data.csv as artifact
        uses: actions/upload-artifact@v4
        with:
          name: data.csv
          path: data.csv
